---
apiVersion: v1
name: operator
version: 12.9.202002191723+d42c6afcade
appVersion: 12-9-202002191723-d42c6afcade
description: Gitlab operator for managing upgrades
keywords:
- gitlab
- operator
home: https://about.gitlab.com/
icon: https://gitlab.com/gitlab-com/gitlab-artwork/raw/master/logo/logo-square.svg
sources:
- https://gitlab.com/gitlab-org/charts/gitlab/tree/master/charts/gitlab/charts/operator
- https://gitlab.com/gitlab-org/charts/components/gitlab-operator
maintainers:
- name: GitLab Inc.
  email: support@gitlab.com
