inherit_gem:
  gitlab-styles:
    - rubocop-default.yml

inherit_from: .rubocop_todo.yml

require:
  - rubocop-rspec

AllCops:
  TargetRubyVersion: 2.7
  # Cop names are displayed in offense messages by default. Change behavior
  # by overriding DisplayCopNames, or by giving the `--no-display-cop-names`
  # option.
  DisplayCopNames: true
  # Style guide URLs are not displayed in offense messages by default. Change
  # behavior by overriding DisplayStyleGuide, or by giving the
  # -S/--display-style-guide option.
  DisplayStyleGuide: false
  Exclude: []

# No rails in charts
Rails:
  Enabled: false

# TODO re-enable and start updating rspec tests
RSpec:
  Enabled: false

# We use git repos in our gemfile, but only our own repos
# TODO: Update the cop to allow us to enable it and allow our groups
Cop/GemFetcher:
  Enabled: false

# We are not concerned with the security of using public in charts but we want to ensure
# Any webserver script we might ship in the future is tested for it
GitlabSecurity/PublicSend:
  Enabled: true
  Exclude:
    - 'spec/**/*'

# Do not introduce global variables.
Style/GlobalVars:
  Enabled: true
  Exclude: []

Style/MultilineIfModifier:
  Enabled: false
