---
apiVersion: v1
name: gitlab
version: 12.9.202002191723+d42c6afcade
appVersion: 12-9-202002191723-d42c6afcade
description: Web-based Git-repository manager with wiki and issue-tracking features.
keywords:
- gitlab
home: https://about.gitlab.com/
icon: https://gitlab.com/gitlab-com/gitlab-artwork/raw/master/logo/logo-square.png
sources:
- https://gitlab.com/gitlab-org/charts/gitlab
maintainers:
- name: GitLab Inc.
  email: support@gitlab.com
