{{- if and .Values.global.gitaly.enabled .Values.global.praefect.enabled -}}
{{- range .Values.global.praefect.virtualStorages -}}
apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: {{ template "fullname" $ }}-{{ .name }}
  namespace: {{ $.Release.Namespace }}
  labels:
    {{- include "gitlab.standardLabels" $ | nindent 4 }}
    storage: {{ .name }}
spec:
  maxUnavailable: {{ default $.Values.maxUnavailable .maxUnavailable }}
  selector:
    matchLabels:
      app: {{ template "name" $ }}
      release: {{ $.Release.Name }}
      storage: {{ .name }}
---
{{- end -}}
{{- end -}}
