{{- if .Values.global.gitaly.enabled -}}
{{- $storages := (dict "name" "default") | list -}}
{{- if .Values.global.praefect.enabled -}}
{{-   $storages = .Values.global.praefect.virtualStorages -}}
{{- end -}}
{{ range $storages }}
apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: {{ include "gitlab.gitaly.serviceName" (dict "context" $ "name" .name) }}
  namespace: {{ $.Release.Namespace }}
  labels:
    {{- include "gitlab.standardLabels" $ | nindent 4 }}
spec:
  maxUnavailable: {{ default $.Values.maxUnavailable .maxUnavailable }}
  selector:
    matchLabels:
      app: {{ template "name" $ }}
      release: {{ $.Release.Name }}
      storage: {{ .name }}
---
{{- end -}}
{{- end -}}
