{{- if .Values.global.gitaly.enabled -}}
{{- range $i, $instance := coalesce .Values.global.gitalyDeploys (list .Values.global.gitaly) }}
apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: {{ $.Release.Name }}-{{default "gitaly" $instance.name }}
  namespace: {{ $.Release.Namespace }}
  labels:
    {{- include "gitlab.standardLabels" $ | nindent 4 }}
spec:
  maxUnavailable: {{ $.Values.maxUnavailable }}
  selector:
    matchLabels:
      app: {{ template "name" $ }}
      release: {{ $.Release.Name }}
      statefulset: {{ $.Release.Name }}-{{default "gitaly" $instance.name }}
{{ printf "---\n" }}
{{- end -}}
{{- end -}}
