#!/bin/bash
set -e

export DEBIAN_FRONTEND=noninteractive
KUBECTL_VERSION=${KUBECTL_VERSION:-1.23.0}
HELM_VERSION=${HELM_VERSION:-3.1.2}
TARGET_DIR=${TARGET_DIR:-"/usr/local/bin"}

apt-get update -qq
apt-get install -y --no-install-recommends \
    curl ca-certificates

if command -v docker; then
    echo "Docker already installed"
    echo "Expected version: 20.10.13"
    docker version
else
    curl -fsSL https://download.docker.com/linux/debian/gpg | gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg
    echo "deb [arch=amd64 signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/debian $(lsb_release -cs) stable" | tee /etc/apt/sources.list.d/docker.list > /dev/null

    apt-get update -qq
    apt install -y docker-ce-cli=5:20.10.13~3-0~debian-${DEBIAN_VERSION:-bullseye}
fi

HELM_INSTALLED_VERSION=""
if command -v helm; then
    echo "Helm already installed"
    echo "Expected version: ${HELM_VERSION}"
    HELM_INSTALLED_VERSION=$(helm version --template '{{.Version}}' | sed -e 's/^v//' )
    echo "Installed version: ${HELM_INSTALLED_VERSION}"
fi

if [ "${STRICT_VERSIONS:+false}" == "true" -a "${HELM_INSTALLED_VERSION}" != "${HELM_VERSION}" ]; then
    echo "Installing helm-${HELM_VERSION}"
    curl -Ls https://get.helm.sh/helm-v${HELM_VERSION}-linux-amd64.tar.gz | tar zxf -
    chmod +x linux-amd64/helm
    mv linux-amd64/helm ${TARGET_DIR}/helm
    rm -rf linux-amd64/
fi

if command -v kubectl; then
    echo "Kubectl already installed"
    echo "Expected version: ${KUBECTL_VERSION}"
    KUBECTL_INSTALLED_VERSION=$(kubectl version --client=true -o yaml | awk '/gitVersion/ { sub("^v","",$2); print $2; }')
    echo "Installed kubectl version: ${KUBECTL_INSTALLED_VERSION}"
fi

if [ "${STRICT_VERSIONS:+false}" == "true" -a "${KUBECTL_INSTALLED_VERSION}" != "${KUBECTL_VERSION}" ]; then
    echo "Installing kubectl-${KUBECTL_VERSION}"
    curl -LsO https://storage.googleapis.com/kubernetes-release/release/v${KUBECTL_VERSION}/bin/linux/amd64/kubectl
    chmod +x kubectl
    mv kubectl ${TARGET_DIR}/kubectl
fi