# Default values for gitlab-chart.
# This is a YAML-formatted file.

global:
  edition: ee
  hosts:
    domain: example.com
    https: true
  # This exists to support template handling
  psql:
    knownDecompositions:
      - main
      - ci

gitlab-runner:
  enabled: false
