{{- if .Values.global.kas.enabled -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "fullname" . }}
  namespace: {{ $.Release.Namespace }}
  labels:
    {{- include "gitlab.standardLabels" . | nindent 4 }}
data:
  config.yaml: |-
{{- (tpl (.Files.Get "default-config.yaml.tpl") . | fromYaml) | merge .Values.customConfig | toYaml | nindent 4 }}
{{- end }}
