---
apiVersion: v1
name: gitaly
version: 13.2.202007100940+421f3644315
appVersion: 8c5463516eec15b68a9065f7f51a9cac2f5e6f3b
description: Git RPC service for handling all the git calls made by GitLab
keywords:
- gitlab
- gitaly
home: https://about.gitlab.com/
icon: https://gitlab.com/gitlab-com/gitlab-artwork/raw/master/logo/logo-square.svg
sources:
- https://gitlab.com/gitlab-org/charts/gitlab/tree/master/charts/gitlab/charts/gitaly
- https://gitlab.com/gitlab-org/build/CNG/tree/master/gitaly
maintainers:
- name: GitLab Inc.
  email: support@gitlab.com
