---
apiVersion: v1
name: gitaly
version: 13.2.202006231110+f81fc143d7b
appVersion: b80283d42b2110bd2e1ea9f590269b0f87fa6787
description: Git RPC service for handling all the git calls made by GitLab
keywords:
- gitlab
- gitaly
home: https://about.gitlab.com/
icon: https://gitlab.com/gitlab-com/gitlab-artwork/raw/master/logo/logo-square.svg
sources:
- https://gitlab.com/gitlab-org/charts/gitlab/tree/master/charts/gitlab/charts/gitaly
- https://gitlab.com/gitlab-org/build/CNG/tree/master/gitaly
maintainers:
- name: GitLab Inc.
  email: support@gitlab.com
