# --- Global settings ---

global:
  image:
    registry: custom.registry.com
    repository: custom-repository

# --- Charts from requirements.yaml ---

# YAML anchor to demonstrate setting image.repository and image.tag
.custom: &custom
  image:
    repository: custom-repository
    tag: 1.2.3-example

certmanager:
  <<: *custom
  cainjector: *custom

gitlab-runner:
  image:
    image: custom-repository
    tag: custom-tag

minio:
  image: custom-repository
  imageTag: custom-tag
  init: *custom
  minioMc:
    image: custom-repository
    tag: custom-tag

nginx-ingress:
  controller: *custom

registry:
    <<: *custom
    init: *custom

postgresql:
  image:
    registry: custom-registry
    repository: custom-image
    tag: 12-custom-tag # start with number to make checkConfig happy
  metrics:
    image:
      registry: custom-registry
      repository: custom-image
      tag: custom-tag

prometheus:
  server: *custom
  configmapReload: *custom

redis:
  image:
    registry: custom-registry
    repository: custom-image
    tag: custom-tag
  metrics:
    image:
      registry: custom-registry
      repository: custom-image
      tag: custom-tag

upgradeCheck: *custom

# If `global.grafana.enabled=true`, uncomment below to set the custom image
# grafana:
#   <<: *custom
#   sidecar:
#     image: custom-repository:custom-tag
