{{- if .Values.global.praefect.enabled -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "fullname" . }}
  namespace: {{ $.Release.Namespace }}
  labels:
    {{- include "gitlab.standardLabels" . | nindent 4 }}
data:
  configure: |
    set -e
    mkdir -p /init-secrets/praefect /init-secrets/shell
    cp -v -r -L /init-config/.gitlab_shell_secret  /init-secrets/shell/.gitlab_shell_secret
    cp -v -r -L /init-config/gitaly_token  /init-secrets/praefect/gitaly_token
  config.toml: |
    # TCP address to listen on
    listen_addr = '0.0.0.0:2305'

    # Optional: export metrics via Prometheus
    prometheus_listen_addr = '0.0.0.0:9652'

    [failover]
    enabled = true
    election_strategy = 'sql'
    read_only_after_failover = false

    [auth]
    token = 'foo'
    transitioning = false

    [logging]
    level = 'debug'
    format = 'json'

    [[virtual_storage]]
    name = 'default'
    [[virtual_storage.node]]
    storage = 'foo'
    address = 'tcp://foo:8075'
    token = 'foo'
    primary = true
    [[virtual_storage.node]]
    storage = 'foo'
    address = 'tcp://foo:8075'
    token = 'foo'
    primary = false
    [[virtual_storage.node]]
    storage = 'foo'
    address = 'tcp://foo:8075'
    token = 'foo'
    primary = false

    [database]
    host = 'foo'
    port = 5432
    user = 'praefect'
    password = 'foo'
    dbname = 'praefect'
    sslmode = 'disable'
{{- end -}}
