{{- if .Values.global.praefect.enabled -}}
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    prometheus.io/port: "9236"
    prometheus.io/scrape: "true"
  labels:
    app: praefect
    chart: gitaly-4.0.1
    heritage: Tiller
    release: ibaum-gitlab
  name: ibaum-gitlab-praefect
  namespace: foo
spec:
  clusterIP: None
  ports:
  - name: praefect
    port: 8075
    protocol: TCP
    targetPort: 8075
  - name: praefect-metrics
    port: 9236
    protocol: TCP
    targetPort: 9236
  selector:
    app: praefect
    release: ibaum-gitlab
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
{{- end -}}
