global:
  hosts:
    domain: (your host IP).nip.io
  ingress:
    configureCertmanager: false

# Don't use certmanager, we'll self-sign
certmanager:
  install: false

# Reduce replicas to 1
nginx-ingress:
  defaultBackend:
    replicaCount: 1
  controller:
    replicaCount: 1
    minAavailable: 1

gitlab-runner:
  # Specify self-signed certificate chain so Runner will connect
  # https://docs.gitlab.com/runner/install/kubernetes.html#providing-a-custom-certificate-for-accessing-gitlab
  # https://docs.gitlab.com/runner/configuration/tls-self-signed.html#supported-options-for-self-signed-certificates
  certsSecretName: self-signed-crt
  # Allow privileged runners for Docker-in-Docker pipelines
  runners:
    privileged: true
