{{ $sharedSecretValues := index .Values "shared-secrets" }}
{{- if and $sharedSecretValues.enabled $sharedSecretValues.rbac.create (not .Values.global.operator.enabled) -}}
{{ include (print $.Template.BasePath "/_shared-secrets-rbac-serviceaccount.yaml") . }}
---
{{ include (print $.Template.BasePath "/_shared-secrets-rbac-role.yaml") . }}
---
{{ include (print $.Template.BasePath "/_shared-secrets-rbac-rolebinding.yaml") . }}
{{- end}}
