{{- if .Values.enabled -}}
{{- include "webservice.datamodel.prepare" $ -}}
{{/* BEGIN range deployments */}}
{{- range $.Values.deployments -}}
{{/*
From here on:
- `.` is `.deployments.xyz` value
- `.name` is the key (xyz)
*/}}
---
apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ template "webservice.fullname.withSuffix" . }}
  namespace: {{ $.Release.Namespace }}
  labels:
    {{- include "gitlab.standardLabels" $ | nindent 4 }}
    {{- include "webservice.labels" . | nindent 4 }}
    {{- include "webservice.commonLabels" . | nindent 4 }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ template "webservice.fullname.withSuffix" . }}
  minReplicas: {{ .hpa.minReplicas }}
  maxReplicas: {{ .hpa.maxReplicas }}
  metrics:
  {{- if not .hpa.customMetrics }}
  - type: Resource
    resource:
      name: cpu
      target:
        type: AverageValue
        averageValue: {{ .hpa.targetAverageValue }}
  {{- else }}
    {{- toYaml .hpa.customMetrics | nindent 4 -}}
  {{- end }}
  behavior:
  {{- if not .hpa.customBehavior }}
    scaleDown:
      stabilizationWindowSeconds: {{ .hpa.scaleDownStabilizationWindowSeconds }}
  {{- else }}
    {{- toYaml .hpa.customBehvior | nindent 4 -}}
  {{- end }}
{{- end }}
{{/* END range deployments */}}
{{- end }}
