{{- if .Values.enabled -}}
{{- include "webservice.datamodel.prepare" $ -}}
{{/* BEGIN range deployments */}}
{{- range $.Values.deployments -}}
{{/*
From here on:
- `.` is `.deployments.xyz` value
- `.name` is the key (xyz)
*/}}
---
{{- if $.Capabilities.APIVersions.Has "autoscaling/v2beta2" }}
apiVersion: autoscaling/v2beta2
{{- else }}
apiVersion: autoscaling/v2beta1
{{- end }}
kind: HorizontalPodAutoscaler
metadata:
  name: {{ template "webservice.fullname.withSuffix" . }}
  namespace: {{ $.Release.Namespace }}
  labels:
    {{- include "gitlab.standardLabels" $ | nindent 4 }}
    {{- include "webservice.labels" . | nindent 4 }}
    {{- include "webservice.commonLabels" . | nindent 4 }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ template "webservice.fullname.withSuffix" . }}
  minReplicas: {{ .hpa.minReplicas }}
  maxReplicas: {{ .hpa.maxReplicas }}
  metrics:
  {{- if not .hpa.customMetrics }}
    - type: Resource
      resource:
        name: cpu
        {{- if $.Capabilities.APIVersions.Has "autoscaling/v2beta2" }}
        target:
          type: AverageValue
          averageValue: {{ .hpa.targetAverageValue }}
        {{- else }}
        targetAverageValue: {{ .hpa.targetAverageValue }}
        {{- end }}
  {{- else }}
    {{- toYaml .hpa.customMetrics | nindent 4 }}
  {{- end }}
  {{- if $.Capabilities.APIVersions.Has "autoscaling/v2beta2" }}
  {{- with .hpa.behaviour }}
  behavior:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- end }}
{{- end }}
{{/* END range deployments */}}
{{- end }}
