{{- if .Values.enabled -}}
{{- include "webservice.datamodel.prepare" $ -}}
{{/* BEGIN range deployments */}}
{{- range $.Values.deployments -}}
{{- $_ := set . "Values" $.Values -}}
{{/*
From here on:
- `.` is `.deployments.xyz` value
- `.name` is the key (xyz)
- `.Values` is `$.Values`
*/}}
---
apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: {{ template "webservice.fullname.suffix" . }}
  namespace: {{ $.Release.Namespace }}
  labels:
    {{- include "gitlab.standardLabels" $ | nindent 4 }}
    {{- include "webservice.labels" . | nindent 4 }}
spec:
  maxUnavailable: {{ .pdb.maxUnavailable }}
  selector:
  matchLabels:
    app: {{ template "name" $ }}
    release: {{ $.Release.Name }}
    {{ include "webservice.labels" . | nindent 4 }}
{{- end }}
{{/* END range deployments */}}
{{- end }}
